version: 2

models:
  - name: inspection_controle__missions
    description: >
      Modèle DBT représentant les missions réalisées dans le cadre de l’Inspection Contrôle,
      enrichi avec les libellés géographiques (commune, département, région) via les référentiels,
      ainsi que le statut juridique des établissements et les types de mission.

    columns:
      - name: reg_cd
        description: "Code de la région d’affectation (ou 'NC' si inconnu)."
      - name: reg_lb
        description: "Libellé de la région d’affectation."
      - name: dep_cd
        description: "Code du département d’affectation."
      - name: dep_lb
        description: "Libellé du département d’affectation."
      - name: com_cd
        description: "Code de la commune d’affectation."
      - name: com_lb
        description: "Libellé de la commune d’affectation."
      - name: "Identifiant de la mission"
        description: "Identifiant unique de la mission issue du SIICEA."
      - name: statut_juridique_lb
        description: "Libellé du statut juridique de l’établissement, ou 'NC' si manquant."
      - name: type_de_mission
        description: "Libellé normalisé du type de mission (ex: Contrôle sur place, Contrôle sur pièces, etc.)."